### PR TITLE
Add missing features for Soundbar

### PR DESCRIPTION
**Pull request by Censored3**
Hello

I was really missing some features to control for my YAS-408 Soundbar, most notably the Subwoofer volume, so I added the features my Soundbar was missing. Most of the groundwork was already in place, it was really just implementing them. Would love to get this integrated upstream.
* Subwoofer volume
* Clear Voice
* 3D Surround
* Sound Program >> This is probably more universal across the models and needs translation strings in HA.

I put everything in seperate commits for easier review - feel free to squash.

I can deliver the getFeatures output for your reference at your request.

### CODE REVIEW

**Comment by Censored3** [comment]
HA en translation strings, combination of MusicCast20 and YAS-408 lists:
```
        "yamaha_musiccast__zone_sound_program": {
            "standard": "Standard",
            "bass_booster": "Bass Booster",
            "stereo": "Stereo",
            "sports": "Sports",
            "game": "Game",
            "music": "Music",
            "tv_program": "TV Program",
            "movie": "Movie"
          }
```

And updated **DEVICE_CLASS_MAPPING**:
```
    "zone_SOUND_PROGRAM": "yamaha_musiccast__zone_sound_program",
```

**Comment by Censored3** [comment]
In the meantime I discovered Sound Program could already be selected through the main entity in HA.
That makes use of the MusicCastDevice.select_sound_mode() method, which I renamed in an attempt to streamline things and only checked this repo for references, not the HA integration - so my change broke that function. I reverted that rename, now.
Imho it's more "clean" and streamlined to also create a separate entity for the sound program, so we can adjust it through automations.

Checked HA for references to the 3D Surround which I renamed as well to streamline, couldn't find any.

**Comment by micha91** [comment]
First of all thanks for your contribution, hopefully I will be able to review it by the mid of this week.

Regarding the selection of sound modes, I think we should keep things as they are, because it could be confusing to have two places to select the sound mode. In addition it is more consistent to the way other integrations set the sound mode. If you want to set the sound mode using automations or scripting, you can already do that by calling the service `media_player.select_sound_mode`. Imho there is only downside of the sound mode in the media_player widget - we cannot display any translations (a discussion regarding this issue can be found [here](https://github.com/home-assistant/architecture/discussions/641).

**Comment by Censored3** [comment]
thanks for your feedback regarding this, that makes sense, and also explains the use of the different method name select_sound_mode vs set_sound_program in the backend.
All right, let's just erase the sound program addition, then.

**Review by micha91 — CHANGES_REQUESTED** [review]
If you remove the sound program capability, we should be good to go. I was able to test subwoofer volume and clear voice on my devices and they seem to work (at least the status updates on changes)

**Comment by Censored3** [comment]
Awesome, I reverted the Sound Program.
I have used these additions quite extensively for the past week, they worked perfectly for me (but I just have the one device supporting them).

**Review by micha91 — APPROVED** [review]

**Pull request merged**
